name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    

    - name: Build and push Docker image
      run: |
        docker build -t thulasiram9790/todo-app .
        docker tag thulasiram9790/todo-app thulasiram9790/todo-app:v2
        docker push thulasiram9790/todo-app:v2

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
        sudo apt update
        sudo apt install docker.io -y
        sudo chmod 777 /var/run/docker.sock
        docker pull thulasiram9790/todo-app:v2
        docker stop $(docker ps -a -q) || true
        docker run -d -p 3000:80 thulasiram9790/todo-app:v2
        EOF
