name: my first workflow
on: push

jobs:
  first-job:
      runs-on: ubuntu-latest
      steps:
       - name: first message
         run: echo "this is my first message"

       - name: listing files
         run: ls

       - name: read the files
         run: cat README.md