name: ascii generator
on: push

jobs:
  build-job:
      runs-on: ubuntu-latest
      steps:
       - name: Checkout
         uses: actions/checkout@v4.2.2
         
       - name: install cowsay
         run: sudo apt install cowsay
              
       - name: cowsay fortune quote generator
         run: fortune | cowsay

       - name: create a txt file 
         run: echo "txt file created" > build.txt
        
       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v4.4.3
         with:
          name: build
          path: build.txt
             
            
  test-job:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v4.2.2
      
        - name: download a Build Artifact
          uses: actions/download-artifact@v4.3.0
          with:
           name: build
        
  
 
