name: ascii generator
on: push

jobs:
  first-job:
      runs-on: ubuntu-latest
      steps:
       - name: Checkout
         uses: actions/checkout@v4.2.2
         
       - name: install cowsay
         run: sudo apt install cowsay
              
       - name: cowsay fortune quote generator
         run: fortune | cowsay

       - name: cowsay list 
         run: cowsay -l
