name: docker login 
on: push


jobs:
  docker-job: 
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      run: echo docker login --username= ${{ secrets.DOCKER_USERNAME }} --password= ${{ secrets.DOCKER_PASSWORD }}
