name: docker login 
on: push
env: 
    DOCKER_USERNAME: thulasiram9790
    DOCKER_PASSWORD: Thulasi@9344

jobs:
  docker-job: 
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
